import TreatmentTemplate, { TreatmentData } from "@/components/TreatmentTemplate";

const data: TreatmentData = {
  slug: "trt",
  heroLabel: "Testosterone Replacement Therapy",
  heroTitle: "Reclaim your edge.",
  heroTitleAccent: "Physician-supervised TRT.",
  heroDescription: "Testosterone cypionate protocols built on a decade of clinical data from Men's Wellness Centers. Real labs, real providers, real results — not a questionnaire and a subscription.",
  heroStats: [
    { value: "10,000+", label: "Patients Treated" },
    { value: "20+", label: "Biomarkers Tested" },
    { value: "4.9", label: "Google Rating" },
  ],
  conditionTitle: "Understanding Low Testosterone",
  conditionDescription: "Testosterone levels in men decline approximately 1-2% per year after age 30. By 45, nearly 40% of men have clinically low testosterone. The symptoms are real — fatigue, weight gain, brain fog, decreased libido — but most primary care physicians dismiss them as 'normal aging.' They're not. Low T is a treatable medical condition, and the data is clear: optimized testosterone levels correlate with improved cardiovascular health, metabolic function, cognitive performance, and quality of life.",
  symptoms: [
    "Persistent fatigue",
    "Unexplained weight gain",
    "Decreased muscle mass",
    "Low libido or ED",
    "Brain fog & poor focus",
    "Irritability & mood changes",
    "Poor sleep quality",
    "Decreased motivation",
  ],
  approachTitle: "How Longentis treats",
  approachAccent: "low testosterone.",
  approachDescription: "No rotating providers. No algorithm-generated protocols. Your dedicated men's health specialist builds and adjusts your protocol based on comprehensive lab data.",
  approachPoints: [
    { title: "Testosterone Cypionate", desc: "The gold standard. Injectable testosterone cypionate dosed based on your labs, not a one-size-fits-all approach." },
    { title: "Comprehensive Lab Panels", desc: "Total and free testosterone, SHBG, estradiol, PSA, CBC, CMP, lipids, thyroid — 20+ biomarkers every time." },
    { title: "Estrogen Management", desc: "Anastrozole when clinically indicated. Monitored through labs, not guesswork." },
    { title: "HCG Protocol", desc: "For men concerned about fertility preservation. Available when medically appropriate." },
    { title: "Quarterly Monitoring", desc: "Repeat labs and provider consultations every 90 days. Your protocol evolves as your body responds." },
    { title: "Same Provider, Every Visit", desc: "One dedicated specialist who knows your history, your labs, and your goals. From first visit through every follow-up." },
  ],
  labPanelTitle: "Your TRT Lab Panel",
  labPanelItems: [
    "Total Testosterone", "Free Testosterone", "SHBG", "Estradiol (E2)", "PSA",
    "CBC with Differential", "CMP", "Lipid Panel", "Thyroid (TSH, T3, T4)",
    "Hemoglobin A1C", "Vitamin D", "B12", "DHEA-S", "LH", "FSH",
    "Prolactin", "IGF-1", "Insulin (Fasting)", "hsCRP", "Ferritin",
  ],
  providerNote: "At-home lab kit or Quest/Labcorp draw. Results reviewed line by line with your provider — not auto-generated by an algorithm.",
  faqs: [
    { q: "Is testosterone replacement therapy safe?", a: "When prescribed and monitored by a qualified provider, TRT has a strong safety profile backed by decades of clinical data. Longentis monitors 20+ biomarkers quarterly to ensure your protocol stays optimized and safe. We track PSA, hematocrit, lipids, and other markers that matter." },
    { q: "How long until I see results?", a: "Most patients report improved energy and mood within 2-4 weeks. Body composition changes (increased muscle, decreased fat) typically become noticeable at 8-12 weeks. Full optimization usually occurs by month 3-6, depending on your starting levels and protocol." },
    { q: "Will TRT affect my fertility?", a: "Testosterone can suppress sperm production. If fertility preservation is a concern, discuss this with your provider during your consultation. HCG protocols are available when medically appropriate to help maintain fertility while on TRT." },
    { q: "Do I need TRT forever?", a: "TRT is typically an ongoing treatment. Once you stop, testosterone levels return to pre-treatment baseline. Your provider will discuss your goals, timeline, and options during your consultation." },
    { q: "What does TRT cost through Longentis?", a: "TRT protocols start at $149/month. This includes your medication, quarterly lab panels, provider consultations, and shipping. No hidden fees. FSA/HSA accepted." },
    { q: "Is this legal in my state?", a: "Yes. Longentis is licensed to practice telehealth in all 50 states. All prescriptions are written by licensed physicians and filled through licensed pharmacies." },
  ],
  ctaTitle: "Ready to check",
  ctaAccent: "your levels?",
  ctaDescription: "Free 5-minute online assessment. No commitment. Your provider reviews your health history and orders labs if you're a candidate.",
  price: "From $149/mo",
  priceNote: "Labs & consultations included",
  relatedTreatments: [
    { title: "Erectile Dysfunction Treatment", href: "/treatments/ed", desc: "FDA-approved PDE5 inhibitors and combination protocols for reliable performance." },
    { title: "Weight Loss Program", href: "/treatments/weight-loss", desc: "GLP-1 medications and metabolic optimization supervised by your dedicated provider." },
  ],
};

const TreatmentTRT = () => <TreatmentTemplate data={data} />;
export default TreatmentTRT;
